- name: Loading role variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install package
  package: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ packages }}"
