- name: Configure vhost
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ server_name }}.conf 
  notify: restart apache 
  
- name: Activate vhost
  file:
    src: /etc/apache2/sites-available/{{ server_name }}.conf
    dest: /etc/apache2/sites-enabled/{{ server_name }}.conf
    state: link
  notify: restart apache
